//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmetShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Product
    {
        public int Id { get; set; }
        public int Id_Order { get; set; }
        public int Id_Product { get; set; }
        public int Product_Count { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
