//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmetShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public int Id { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string UnitOfMeasurement { get; set; }
        public int Cost { get; set; }
        public int MaxSale { get; set; }
        public string Manufacturer { get; set; }
        public string Provider { get; set; }
        public string Category { get; set; }
        public Nullable<int> CurrentSale { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Description { get; set; }
        public byte[] Preview { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
    }
}
